### ISSUE TITLE
Package not found: Conda could not find

### ISSUE THREAD

**Issue by steveoni** [amueller/word_cloud#269] opened 2017-05-28 10:56 UTC
i try also to use conda to install on linux
conda install -c https://conda.anaconda.org/amueller wordcloud

but i got  an error:
PackageNotFoundError: Package not found: Conda could not find '

**Comment by amueller** [comment] 2017-05-29 15:34
There is currently no conda package for linux. Happy to take a pull request.

**Comment by amueller** [comment] 2017-05-29 15:35
Closing as duplicate of #232.

**Closed by amueller** 2017-05-29 15:35 UTC
