### ISSUE TITLE
Cannot run others mask images

### ISSUE THREAD

**Issue by 62ramya** [amueller/word_cloud#37] opened 2014-12-17 09:29 UTC
I have tried to use other images in marked.py instead alice_mask. I am getting the following error.

ValueError: Buffer has wrong number of dimensions (expected 2, got 3)

I used imread(path.join(d, "try1.png"), flatten=True) in marked.py, I am getting empty image.

**Comment by ashokgadri** [comment] 2015-01-09 17:28
This error will come due to bit depth of image.
You have to use image with only 8-bit depth.
Convert image into pure blank and white image with 8-bit depth
Code to Convert image into black and white with 8-bit depth
image_file = Image.open('img.ong')
image_file = image_file.convert("L") # convert image to black and white
image_file.mode = "L"
image_file = image_file.point(lambda x: 0 if x<128 else 255)
image_file.save('grey.png')

**Comment by amueller** [comment] 2015-01-09 18:32
Thanks for the hing @ashokgadri Would you like to contribute a fix with regression test?

**Comment by ashokgadri** [comment] 2015-01-10 12:35
@amueller Yes I would like to contribute in this project. I Already did a desktop app with selecting image and convert it into b/w and generate cloud.

**Comment by amueller** [comment] 2015-01-10 20:03
cool. Just make a pull request that ensures the correct bitness of the image.

**Comment by amueller** [comment] 2015-04-29 02:47
Should be fixed in master.

**Closed by amueller** 2015-04-29 02:47 UTC
