### ISSUE TITLE
Wheel file for cp39_win_amd_64 is missing?

### ISSUE THREAD

**Issue by elitist7** [amueller/word_cloud#617] opened 2021-01-02 15:19 UTC
New Wheels should be available now.

_Originally posted by @amueller in https://github.com/amueller/word_cloud/issues/604#issuecomment-725686193_

**Comment by amueller** [comment] 2021-01-04 19:53
Duplicate of #614, sorry I didn't get around to looking into the build issues yet, any help appreciated.

**Comment by amueller** [comment] 2022-06-27 19:07
Wheel should finally be up now: https://pypi.org/project/wordcloud/#files

**Closed** 2023-04-27 21:01 UTC
