### ISSUE TITLE
compatibility error with python 3.8 and above

### ISSUE THREAD

**Issue by KailasMahavarkar** [amueller/word_cloud#624] opened 2021-02-17 18:48 UTC
#### Description
(venv) PS C:\zero\venv\Scripts> pip install wordcloud
Collecting wordcloud
  Using cached wordcloud-1.8.1.tar.gz (220 kB)
Requirement already satisfied: numpy>=1.6.1 in c:\zero\venv\lib\site-packages (from wordcloud) (1.20.1)
Requirement already satisfied: pillow in c:\zero\venv\lib\site-packages (from wordcloud) (8.1.0)
Requirement already satisfied: matplotlib in c:\zero\venv\lib\site-packages (from wordcloud) (3.3.4)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\zero\venv\lib\site-packages (from matplotlib->wordcloud) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\zero\venv\lib\site-packages (from matplotlib->wordcloud) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\zero\venv\lib\site-packages (from matplotlib->wordcloud) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\zero\venv\lib\site-packages (from matplotlib->wordcloud) (1.3.1)
Requirement already satisfied: six in c:\zero\venv\lib\site-packages (from cycler>=0.10->matplotlib->wordcloud) (1.15.0)
Using legacy 'setup.py install' for wordcloud, since package 'wheel' is not installed.
Installing collected packages: wordcloud
    Running setup.py install for wordcloud ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\zero\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kai\\AppData\\Local\\Temp\\pip-install-cbbey9m2\\wordcloud_e1254508dbc84b4ebce07a5a0e7579b0\\setup.py'"'"'; __file__='"'"'C:\\Users\\kai\\AppData\\Local\\Temp\\pip-install-cbbey9m2\\wordcloud_e1254508dbc84b4ebce07a5a0e7579b0\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kai\AppData\Local\Temp\pip-record-840y5lr7\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\zero\venv\include\site\python3.9\wordcloud'
         cwd: C:\Users\kai\AppData\Local\Temp\pip-install-cbbey9m2\wordcloud_e1254508dbc84b4ebce07a5a0e7579b0\
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\tokenization.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\_version.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\__init__.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\__main__.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\stopwords -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.9\wordcloud
    UPDATING build\lib.win-amd64-3.9\wordcloud/_version.py
    set build\lib.win-amd64-3.9\wordcloud/_version.py to '1.8.1'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\zero\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kai\\AppData\\Local\\Temp\\pip-install-cbbey9m2\\wordcloud_e1254508dbc84b4ebce07a5a0e7579b0\\setup.py'"'"'; __file__='"'"'C:\\Users\\kai\\AppData\\Local\\Temp\\pip-install-cbbey9m2\\wordcloud_e1254508dbc84b4ebce07a5a0e7579b0\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kai\AppData\Local\Temp\pip-record-840y5lr7\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\zero\venv\include\site\python3.9\wordcloud' Check the logs for full command output.
(venv) PS C:\zero\venv\Scripts>

#### Steps/Code to Reproduce
install latest version of python(3.9.1) as per today
pip install wordcloud

**Comment by amueller** [comment] 2021-02-17 19:54
Duplicate of #614, sorry, still no new wheels, I'll try for it this weekend.

**Comment by amueller** [comment] 2021-02-17 19:55
Also: If you want to pitch in, help is more than welcome. We probably need to move CI to github actions.

**Comment by PabloRees** [comment] 2021-04-13 14:43
I've got the same issue. Any instruction available? I'm using Python 3.9 and Windows 10.

**Comment by amueller** [comment] 2021-04-14 01:54
@PabloRees you can compile from source by installing the Visual C++ 14.0 compiler as mentioned in the error message.
Sorry I haven't fixed this up yet :-/

**Comment by saadpython** [comment] 2021-04-21 06:07
I am also having the same issue:


ERROR: Command errored out with exit status 1:
     command: 'c:\users\syedsaadali\pycharmprojects\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\SyedSaadAli\\AppDa
ta\\Local\\Temp\\pip-install-m25lj0z0\\wordcloud_16231e3302e943cb9bdd2e5d827dc94e\\setup.py'"'"'; __file__='"'"'C:\\Users\\SyedSaadAli\\AppData\\Local\\Temp\\pip-inst
all-m25lj0z0\\wordcloud_16231e3302e943cb9bdd2e5d827dc94e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"
'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\SyedSaadAli\AppData\Local\Temp\pip-record-txrh2pi3\install-record.txt' -
-single-version-externally-managed --compile --install-headers 'c:\users\syedsaadali\pycharmprojects\venv\include\site\python3.9\wordcloud'
         cwd: C:\Users\SyedSaadAli\AppData\Local\Temp\pip-install-m25lj0z0\wordcloud_16231e3302e943cb9bdd2e5d827dc94e\
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\tokenization.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\_version.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\__init__.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\__main__.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\stopwords -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.9\wordcloud
    UPDATING build\lib.win-amd64-3.9\wordcloud/_version.py
    set build\lib.win-amd64-3.9\wordcloud/_version.py to '1.8.1'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------




In fact I have already installed Python Latest version:
i.e. Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32




While Installing 'wordcloud', it gives same error as above.


Please help in this case.


Thanks.

**Comment by PabloRees** [comment] 2021-04-21 09:29
Hi Sayed

I ended up using a Python 3,7 virtual environment and it worked.

Best
Pablo

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by amueller** [comment] 2023-04-27 21:00
This should have long been fixed. Let me know if there's still any issues.

**Closed by amueller** 2023-04-27 21:00 UTC
