### ISSUE TITLE
Value Error: ImageColorGenerator is smaller than the canvas

### ISSUE THREAD

**Issue by divyam28** [amueller/word_cloud#378] opened 2018-05-19 19:20 UTC
#### Description
Hey I am definitely sure that my ImageColorGenerator is bigger than my canvas and I even tried to change the canvas width height to more and less but I am always getting this value error no matter what. Here is my code - 

Example:
```
mask3 = np.array(Image.open(path.join(d, "test7.png")))
wc = WordCloud(background_color="white", max_words=1000, mask=mask3,stopwords=q,
               max_font_size=150, random_state=42)
wc.generate(str4)
# create coloring from image
image_colors = ImageColorGenerator(mask3)
print(image_colors.image.shape)
print(wc.width, wc.height)
plt.figure(figsize=[5,5])
plt.tight_layout(pad=0)
plt.imshow(wc.recolor(color_func=image_colors), interpolation="bilinear")
plt.axis("off")
plt.show()

```
#### Explanation
This Image test7 here is 800*800 and I know that default canvas is 400*200
I have another image which is 900*900 and that is working perfectly.

Can you explain me as to how this is working and what is happening:

#### output for test7 image ( the red thing with eyes)
(800, 800, 4)
400 200

### Images
This is the image with which it is working perfectly
![test1](https://user-images.githubusercontent.com/22813209/40272175-3ec09de2-5bc7-11e8-8771-799753eb259f.jpg)
This is the image which is showing error
![test7](https://user-images.githubusercontent.com/22813209/40272176-3f1edb5a-5bc7-11e8-8233-b969dd63bcd7.png)
This is the image to which I actually want to do it ultimately this image is 500*306
![test8](https://user-images.githubusercontent.com/22813209/40272192-6832c5c4-5bc7-11e8-8257-54a4536dfef9.png)

Please help

**Comment by divyam28** [comment] 2018-05-19 19:33
No the imports are there this is one of the cells in my jupyter notebook

### Traceback 

```
> (800, 800, 4)
> 400 200
> 
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-128-d9b3201b8e1c> in <module>()
>      20 plt.figure(figsize=[5,5])
>      21 plt.tight_layout(pad=0)
> ---> 22 plt.imshow(wc.recolor(color_func=image_colors), interpolation="bilinear")
>      23 plt.axis("off")
>      24 plt.show()
> 
> ~/anaconda3/lib/python3.6/site-packages/wordcloud/wordcloud.py in recolor(self, random_state, color_func, colormap)
>     638                                     font_path=self.font_path))
>     639                         for word_freq, font_size, position, orientation, _
> --> 640                         in self.layout_]
>     641         return self
>     642 
> 
> ~/anaconda3/lib/python3.6/site-packages/wordcloud/wordcloud.py in <listcomp>(.0)
>     637                                     random_state=random_state,
>     638                                     font_path=self.font_path))
> --> 639                         for word_freq, font_size, position, orientation, _
>     640                         in self.layout_]
>     641         return self
> 
> ~/anaconda3/lib/python3.6/site-packages/wordcloud/color_from_image.py in __call__(self, word, font_size, font_path, position, orientation, **kwargs)
>      53         if not reshape.any():
>      54             if self.default_color is None:
> ---> 55                 raise ValueError('ImageColorGenerator is smaller than the canvas')
>      56             return "rgb(%d, %d, %d)" % tuple(self.default_color)
>      57         color = np.mean(reshape, axis=0)
> 
> ValueError: ImageColorGenerator is smaller than the canvas
> 
```

**Comment by divyam28** [comment] 2018-05-19 19:36
If I use test1 file which I attached. The file with the trees : 
```
mask3 = np.array(Image.open(path.join(d, "test1.jpg")))
wc = WordCloud(background_color="white", max_words=1000, mask=mask3,stopwords=q,
               max_font_size=150, random_state=42)
wc.generate(str4)
# create coloring from image
image_colors = ImageColorGenerator(mask3)
print(image_colors.image.shape)
print(wc.width, wc.height)
plt.figure(figsize=[5,5])
plt.tight_layout(pad=0)
plt.imshow(wc.recolor(color_func=image_colors), interpolation="bilinear")
plt.axis("off")
plt.show()
```

I get what I want and this: 
(900, 900, 3)
400 200

Its 900*900

![image](https://user-images.githubusercontent.com/22813209/40272395-067d15c0-5bca-11e8-9540-760d49f60945.png)

**Comment by amueller** [comment] 2018-05-19 20:06
I asked for a self-contained example so I could run it. It doesn't really help me if the imports are somewhere else in your jupyter notebook.

**Comment by amueller** [comment] 2018-05-19 20:12
OK so I ran
```python
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from wordcloud import WordCloud, ImageColorGenerator

mask3 = np.array(Image.open('40272176-3f1edb5a-5bc7-11e8-8233-b969dd63bcd7.png'))
wc = WordCloud(background_color="white", max_words=1000, mask=mask3,
               max_font_size=150, random_state=42)
wc.generate("ASF  ASDFASDF  ASDF ASDF ")
# create coloring from image
image_colors = ImageColorGenerator(mask3)
print(image_colors.image.shape)
print(wc.width, wc.height)
plt.figure(figsize=[5,5])
plt.tight_layout(pad=0)
plt.imshow(wc.recolor(color_func=image_colors), interpolation="bilinear")
plt.axis("off")
plt.show()
```
with the red image that is 800x800 and it's not showing an error..

**Comment by divyam28** [comment] 2018-05-19 20:15
https://github.com/divyam28/testwordcloud here I uploaded all my code

**Comment by amueller** [comment] 2018-05-19 20:16
that's not a minimum example: https://stackoverflow.com/help/mcve

**Comment by divyam28** [comment] 2018-05-19 20:16
So you're saying I have some issue in my text file?

**Comment by divyam28** [comment] 2018-05-19 20:25
alright im sorry. wait ill make one and send

**Comment by divyam28** [comment] 2018-05-19 20:36
https://github.com/divyam28/testwordcloud Here

**Comment by amueller** [comment] 2018-05-19 20:41
works for me. Which version of wordcloud are you using? Try installing from github.

**Comment by amueller** [comment] 2018-05-19 20:41
though actually the pipy version is pretty up to date.

**Comment by divyam28** [comment] 2018-05-19 20:45
I installed from Pip. If I use random 5-6 words during making the word cloud it shows no error but if I use my text file it shows me this error. Might have any idea why?

**Comment by amueller** [comment] 2018-05-19 20:46
running the code from the repo you just send me?

**Comment by divyam28** [comment] 2018-05-19 20:47
Yep and the text file I uploaded on the repo

**Comment by amueller** [comment] 2018-05-23 17:16
Hm sorry I can't reproduce.

**Comment by divyam28** [comment] 2018-05-28 02:41
Did you try with the text file and image I uploaded?

**Comment by amueller** [comment] 2018-05-28 14:41
Yes, with your exact repository.

**Comment by DaiMaoTsai** [comment] 2018-06-05 01:17
Hey,  First, thanks for repo!  

I wanted to chime in and say I think I have the same problem.  At least it's with an odd sized picture, with the same traceback.  I saw that the error gets thrown if there's no default color, so I gave it one (bright red) and that at least gets around the throw and generates some output.  What's interesting is that it only used my default color for one tiny word *in the middle of the picture*, i.e. not at the edge like I would have thought if the mask were too small.  Maybe it's not the size, but the color value of the mask at that point?

Sorry I don't have time to generate a test case for you, but reading the thread I'm convinced it's the same problem.

**Comment by amueller** [comment] 2018-06-06 15:04
@DaiMaoTsai can you please try to provide a self-contained example so I may reproduce?

**Comment by DaiMaoTsai** [comment] 2018-06-06 17:51
@amueller did you read my comment?  I can clarify, but really that should be enough.  It is a simple bug, and I even provided a workaround.

**Comment by amueller** [comment] 2018-06-06 18:19
I'd rather fix the bug than have a work-around, so being able to reproduce and debug would be good.

**Comment by DaiMaoTsai** [comment] 2018-06-06 18:30
Attached Jupyter notebook and mask file provide a minimal example.  Be sure to rename '.txt' to '.ipynb' and put the mask file the the appropriate place.


[Debug+wordcloud+ipynb.txt](https://github.com/amueller/word_cloud/files/2077636/Debug.wordcloud.ipynb.txt)
![test_mask](https://user-images.githubusercontent.com/6005016/41057656-8f977638-697c-11e8-8177-844e24e9abc4.png)

**Comment by amueller** [comment] 2018-06-06 18:33
Thanks, just created one from your description:
```python
import numpy as np
from wordcloud import WordCloud, ImageColorGenerator

mask = np.zeros((50, 50, 3))
wc = WordCloud(background_color="white", max_words=1000, mask=mask,
               max_font_size=150, random_state=42)
wc.generate("ASF  ASDFASDF  ASDF ASDF ")
image_colors = ImageColorGenerator(mask)
```

**Comment by amueller** [comment] 2018-06-06 18:54
Fixed in #391.

**Comment by amueller** [comment] 2018-06-06 18:56
Thanks for your reports but they would have been *much* easier to investigate if you'd have provided a minimum reproducing example, such as the 4 lines I gave above.

**Closed** 2018-06-06 19:02 UTC

**Comment by cipher813** [comment] 2018-07-02 01:49
Hello, I seem to be having a similar problem.  My code is as follows:

`def generate_wordcloud(text):  
    mask=np.array(Image.open('../data/note.png'))
    image_colors=ImageColorGenerator(mask)
    wc = WordCloud(background_color='white',
                          color_func=image_colors,
                          max_words=2000,
                          mask=mask,
                          colormap='magma',
                          stopwords=sw).generate(text)
    
    plt.imshow(wc, 
               interpolation="bilinear") 
    plt.axis("off")
    title = "Topic {}".format(i)
    plt.title(title,fontweight='bold',fontsize=16) `

And traceback as follows:

`------------------------------------------------------
ValueError           Traceback (most recent call last)
<ipython-input-83-8177ddc36385> in <module>()
     12     text = ''.join(cluster_map[cluster_map.cluster==i].comments)
     13 
---> 14     generate_wordcloud(text)
     15 
     16 filepath3 = "../charts/wc_kmctsne.png"

<ipython-input-79-768803510c3e> in generate_wordcloud(text)
      7                           mask=mask,
      8                           colormap='magma',
----> 9                           stopwords=sw).generate(text)
     10 
     11     plt.imshow(wc, 

~/anaconda3/envs/recommender/lib/python3.6/site-packages/wordcloud/wordcloud.py in generate(self, text)
    569         self
    570         """
--> 571         return self.generate_from_text(text)
    572 
    573     def _check_generated(self):

~/anaconda3/envs/recommender/lib/python3.6/site-packages/wordcloud/wordcloud.py in generate_from_text(self, text)
    551         """
    552         words = self.process_text(text)
--> 553         self.generate_from_frequencies(words)
    554         return self
    555 

~/anaconda3/envs/recommender/lib/python3.6/site-packages/wordcloud/wordcloud.py in generate_from_frequencies(self, frequencies, max_font_size)
    474                                           orientation=orientation,
    475                                           random_state=random_state,
--> 476                                           font_path=self.font_path))
    477             # recompute integral image
    478             if self.mask is None:

~/anaconda3/envs/recommender/lib/python3.6/site-packages/wordcloud/color_from_image.py in __call__(self, word, font_size, font_path, position, orientation, **kwargs)
     53         if not reshape.any():
     54             if self.default_color is None:
---> 55                 raise ValueError('ImageColorGenerator is smaller than the canvas')
     56             return "rgb(%d, %d, %d)" % tuple(self.default_color)
     57         color = np.mean(reshape, axis=0)

ValueError: ImageColorGenerator is smaller than the canvas`

Please do let me know if I can provide any further information - I look forward to hearing your thoughts.

**Comment by amueller** [comment] 2018-07-02 16:03
@cipher813 have you tried the wordcloud version from github?

**Comment by kimyoungjin06** [comment] 2018-07-03 05:38
Hello! @amueller 

I have same error.

I installed using Conda wc--1.4.1
-----------------------------
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /opt/conda:

The following NEW packages will be INSTALLED:

    wordcloud: 1.4.1-py36_0 conda-forge

wordcloud-1.4. 100% |################################| Time: 0:00:01 186.49 kB/s
---------------------------------------

And my code is bottom.

First code is working perfectly!

```python
icon = Image.open(icon_path).convert("RGBA")
mask = Image.new("RGB", icon.size, (255,255,255))
mask.paste(icon,icon)
mask = np.array(mask)

wc = WordCloud(font_path=font_path, background_color="white", max_words=20000, mask=mask,
               max_font_size=300, random_state=42)

image_colors = ImageColorGenerator(coloring)
# generate word cloud
wc.generate_from_frequencies(word_dict)
wc.recolor(color_func=color_func, random_state=3)
wc.to_file("korea_wc.png")
```

But I want to recolor.

```python
coloring = np.array(Image.open(icon_path))
wc.recolor(color_func=image_colors)
wc.to_file("korea_wc2.png")
```
This code is not working with this error message.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-166-c6e590858aba> in <module>()
      7 # # generate word cloud
      8 # wc.generate_from_frequencies(word_dict)
----> 9 wc.recolor(color_func=image_colors)
     10 wc.to_file("korea_wc2.png")

/opt/conda/lib/python3.6/site-packages/wordcloud/wordcloud.py in recolor(self, random_state, color_func, colormap)
    638                                     font_path=self.font_path))
    639                         for word_freq, font_size, position, orientation, _
--> 640                         in self.layout_]
    641         return self
    642 

/opt/conda/lib/python3.6/site-packages/wordcloud/wordcloud.py in <listcomp>(.0)
    637                                     random_state=random_state,
    638                                     font_path=self.font_path))
--> 639                         for word_freq, font_size, position, orientation, _
    640                         in self.layout_]
    641         return self

/opt/conda/lib/python3.6/site-packages/wordcloud/color_from_image.py in __call__(self, word, font_size, font_path, position, orientation, **kwargs)
     53         if not reshape.any():
     54             if self.default_color is None:
---> 55                 raise ValueError('ImageColorGenerator is smaller than the canvas')
     56             return "rgb(%d, %d, %d)" % tuple(self.default_color)
     57         color = np.mean(reshape, axis=0)

ValueError: ImageColorGenerator is smaller than the canvas
```

**Comment by amueller** [comment] 2018-07-03 12:07
As I said above, this is fixed in the github version.

**Comment by kimyoungjin06** [comment] 2018-07-03 21:54
Um.. I was install from github version,
But still I get the Error. 
And I find the solution.
```python
image_colors = ImageColorGenerator(coloring)
image_colors.default_color = [0.6,0.6,0.6] # any value for RGB
# generate word cloud
wc.generate_from_frequencies(word_dict)
wc.recolor(None,image_colors)
```

**Comment by amueller** [comment] 2018-07-04 19:01
Can you provide an example to reproduce the error from the github version please?

**Comment by kimyoungjin06** [comment] 2018-07-05 01:12
This is a Code.

```python
coloring = np.array(Image.open(icon_path))

wc = WordCloud(font_path=font_path, background_color="white", max_words=20000, mask=coloring,
               max_font_size=300, random_state=42)

image_colors = ImageColorGenerator(coloring)
# image_colors.default_color = [0.6,0.6,0.6]

wc.recolor(None,image_colors)
wc.to_file("korea_wc22.png")
```

This is Error message

```log
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-247-0124be2f142c> in <module>()
      8 # # generate word cloud
      9 # wc.generate_from_frequencies(word_dict)
---> 10 wc.recolor(None,image_colors)
     11 wc.to_file("korea_wc22.png")

/opt/conda/lib/python3.6/site-packages/wordcloud/wordcloud.py in recolor(self, random_state, color_func, colormap)
    638                                     font_path=self.font_path))
    639                         for word_freq, font_size, position, orientation, _
--> 640                         in self.layout_]
    641         return self
    642 

/opt/conda/lib/python3.6/site-packages/wordcloud/wordcloud.py in <listcomp>(.0)
    637                                     random_state=random_state,
    638                                     font_path=self.font_path))
--> 639                         for word_freq, font_size, position, orientation, _
    640                         in self.layout_]
    641         return self

/opt/conda/lib/python3.6/site-packages/wordcloud/color_from_image.py in __call__(self, word, font_size, font_path, position, orientation, **kwargs)
     53         if not reshape.any():
     54             if self.default_color is None:
---> 55                 raise ValueError('ImageColorGenerator is smaller than the canvas')
     56             return "rgb(%d, %d, %d)" % tuple(self.default_color)
     57         color = np.mean(reshape, axis=0)

ValueError: ImageColorGenerator is smaller than the canvas
```

I did install from this repo using wget.

```
wget https://github.com/amueller/word_cloud/archive/master.zip
unzip master.zip
rm master.zip
cd word_cloud-master
```

**Comment by amueller** [comment] 2018-07-12 17:57
Sorry for the slow reply. Can you please provide a self-contained example?
It also looks like you never called any of the generate functions, i.e. there's no text?

**Comment by kimyoungjin06** [comment] 2018-07-13 00:17
## Data structure:
```
# Structure of word_dict
{
word1 : count,
word2 : count,
...
word_N : count
}
```

## Full code
```python
# IMPORT PACKAGES
import numpy as np
import random
from PIL import Image
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
from palettable.colorbrewer.qualitative import Dark2_8

# FONT, ICON, MASK
font = "a엄마의편지B"
font_path = "%s.ttf" % font

icon = "korea2"
icon_path = "%s.png" % icon

icon = Image.open(icon_path).convert("RGBA")
mask = Image.new("RGB", icon.size, (255,255,255))
mask.paste(icon,icon)
mask = np.array(mask)

# Word Cloud with colored mask
wc = WordCloud(font_path=font_path, background_color="white", max_words=20000, mask=mask,
               max_font_size=300, random_state=42)

coloring = np.array(Image.open(icon_path))
image_colors = ImageColorGenerator(coloring)
image_colors.default_color = [0.6,0.6,0.6] # Important!!! at 2018.07.07

# Generate word cloud
wc.generate_from_frequencies(word_dict)
wc.recolor(None,image_colors)
wc.to_file("output.png")
```

## output
![image](https://user-images.githubusercontent.com/20521264/42666027-65986fa4-867d-11e8-8da3-c4359faeeac4.png)

**Comment by arronvera** [comment] 2018-10-08 08:59
I also have the error.how to solve it?

**Comment by amueller** [comment] 2018-10-08 13:18
@arronvera what version are you using?

**Comment by woreom** [comment] 2020-03-04 16:58
> that's not a minimum example: https://stackoverflow.com/help/mcve

It seems that the error raises from min_font_size, max_font_size changing them will result in not getting an error!

**Comment by SAGIRI-kawaii** [comment] 2021-01-29 08:27
Hello, I think I have the same problem
I'm using wordcloud-1.8.1
I found that this error is triggered when I use the `wordcloud.generate_from_frequencies` method

This is a code:
```python
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from wordcloud import WordCloud, ImageColorGenerator


def test(frequencies_dict: dict):
    color_mask = np.array(Image.open("./back.jpg"))
    wc = WordCloud(
        mask=color_mask, background_color='white'
    )
    wc.generate_from_frequencies(frequencies_dict)
    image_colors = ImageColorGenerator(color_mask)
    plt.imshow(wc.recolor(color_func=image_colors), interpolation="bilinear")
    plt.axis("off")
    wc.to_file('./temp.png')
```

This is the frequencies_dict I used：
```
{'setu': 143, 'test': 51, '总结': 51, 'SAGIRI': 47, 'pd': 42, '': 32, '月内': 32, 'abc': 31, '番剧': 30, '添加': 27,
       '生日': 26, '涩图': 25, '2020': 21, 'super': 16, '年内': 16, 'print': 15, 'py': 15, 'github': 14, '1': 13,
       '2000-04-27': 13, 'test1': 13, 'magnet': 11, '搜番': 11, 'from': 10, 'status': 10, 'test2': 10, '什么': 10, '消息': 10,
       'douban': 9, 'sql:select': 9, '啊这': 9, '搜图': 9, '日系': 9, '蕾娜': 9, 'bizhi': 8, '996': 7, '><': 7, '不错': 7,
       '网络': 7, '计算机': 7, '`time`': 6, 'by': 6, 'desc': 6, 'imgcalled': 6, 'limit': 6, 'myinfo': 6, 'order': 6,
       'picUrl': 6, '伊蕾娜': 6, '点歌': 6, '超炮': 6, '[XML': 5, 'code': 5, 'exec(s': 5, 'https': 5, 'pc': 5, 'steam': 5,
       '  你是谁': 4, '75976909': 4, 'action': 4, 'qr': 4, 'setting': 4, 'setting.debug.Enable': 4,
       'setting.longTextType.text': 4, 'shutdown': 4, 'summary': 4, 'trend': 4, '今天': 4, '你好': 4, '微博': 4, '热榜': 4,
       '签到': 4, '草': 4, '阿里': 4, '0.08808016777038574': 3, '85217085': 3, 'APP': 3, 'GraiaMiraiPlatform': 3,
       'Program': 3, 'advertiser': 3, 'aid': 3, 'execution': 3, 'id': 3, 'layout': 3, 'lemon': 3, 'myInfo': 3,
       'setting.countLimit.Enable': 3, 'setting.repeat': 3, 'time': 3, '历史': 3, '好耶': 3, '怎么': 3, '群月': 3, "'s": 2,
       '/item': 2, '01-09': 2, '04-27': 2, '1.0': 2, '123': 2, '1日': 2, '2000-04-21': 2, '300': 2, '::-': 2,
       '><item': 2, '?xml': 2, 'Enable': 2, 'Monster': 2, 'UTF-8': 2, '][': 2, 'adverSign': 2, 'appid': 2, 'bot': 2,
       'brief': 2, 'encoding': 2, "end=''": 2, 'flag=': 2, 'icon': 2, 'msg': 2, 'multiMsgFlag=': 2, 'name': 2, 'ph': 2,
       'python': 2, 'real': 2, 'real*5': 2, 'realHighq': 2, 'restart': 2, 'rhq': 2, 'serviceID': 2,
       'setting.bizhi.Enable': 2, 'setting.longTextType.img': 2, 'setu*5': 2, 'so': 2, 'source': 2, 'sourceMsgId': 2,
       "standalone='yes'": 2, 'templateID': 2, 'title': 2, 'url=': 2, 'v': 2, 'version': 2, 'weibo': 2, '人家': 2,
       '删除': 2, '天天': 2, '好用': 2, '手机': 2, '教务': 2, '日文': 2, '时候': 2, '查看': 2, '标题': 2, '热搜': 2, '笑话': 2,
       '考研': 2, '聊天': 2, '试试': 2, '通知': 2, '雾涩': 2, '魔女': 2, '  ': 1, '  你是谁啊': 1, '  摸': 1, '  爱你哦': 1,
       '/item><item': 1, '100&amp;uin=': 1, '1027&k=fbN1lngy': 1, '12': 1, '12345': 1, '124': 1, '13787': 1,
       '1764362678': 1, '18751': 1, '2000-01-09': 1, '2000-04': 1, '28': 1, '2日': 1, '3274549506': 1, '4423': 1,
       '550': 1, '62797122D': 1, '672': 1, '69': 1, '80de7427e03934': 1, '84&dn=': 1, '999': 1, ':-5]': 1, '://': 1,
       '://card/show': 1, '://github.com/mamoe/mirai': 1, '://m.jb51.net/article/139575.htm': 1, '://qzs': 1,
       '://tv.cctv.com': 1, '></msg>': 1, '></msg>': 1, 'D663': 1, 'AGPL': 1, 'BF645462EE': 1, 'CA29': 1,
       'CE1D': 1, 'COMI': 1, 'C☆13': 1, 'DFFCC09258DD05': 1, 'DL版': 1, 'Disable': 1, 'E19A': 1, 'F2E1A8ED': 1,
       'FEBFE': 1, 'GroupFiledid': 1, 'Hunter': 1, 'INfO': 1, 'Moster': 1, 'Process.revoke': 1, 'QAQ': 1, 'QQ': 1,
       'Revoke.Enable': 1, '[焼': 1, ']请': 1, 'b4': 1, 'b7975f': 1, 'bg': 1, 'color': 1, 'cookbook': 1, 'counter': 1,
       'cover': 1, 'dls': 1, 'ef': 1, 'endacsd': 1, 'false': 1, 'ff': 1, 'filesize': 1, 'fneo-014': 1, 'fs': 1,
       'furry': 1, 'gc': 1, 'help': 1, 'hidden=': 1, 'hr': 1, 'image': 1, 'jq': 1, 'leet': 1,
       'live/cctvchild/m/[XML': 1, 'local': 1, 'maxHeight': 1, 'maxWidth': 1, 'md': 1, 'minHeight': 1, 'minWidth': 1,
       'mirai': 1, 'miraiAndroid': 1, 'mode': 1, 'mq': 1, 'my': 1, 'path': 1, 'picture': 1, 'png': 1, 'ps': 1,
       'pslcard?src': 1, 'qapi': 1, 'qq.com': 1, 'qq.com/ac': 1, 'qzone_v5/client/auth_icon': 1, 'select': 1,
       'setting.anti': 1, 'setting.bizhi.Disable': 1, 'setting.compile.Enable': 1, 'setting.countLimit.Disable': 1,
       'setting.r18': 1, 'setting.r18.Disable': 1, 'setting.r18.Enable': 1, 'setting.s.': 1, 'setting.search.Enable': 1,
       'setting.searchBangumi.Enable': 1, 'setu18': 1, 'seyu': 1, 'sharecard&amp;version': 1, 'size': 1, 'sql': 1,
       'style': 1, 'sx123456': 1, 'type=interna1&amp;source': 1, 'umauc/githubot': 1, 'uuid': 1, 'w=': 1, 'wv': 1,
       'zhihu': 1, '。。。': 1, 'あお': 1, 'きた': 1, 'くざ': 1, 'ちん': 1, 'てジ': 1, 'ぽや': 1, 'みぽ': 1, 'むし': 1, 'りん': 1, 'ん編': 1,
       'イカ': 1, 'イジ': 1, 'ガー': 1, 'クス': 1, 'ゾ愛': 1, 'ツァー': 1, 'パン': 1, 'ボコ': 1, 'マヤ+': 1, 'ャマ': 1, 'ルズ': 1, '一个': 1,
       '不够': 1, '世界': 1, '中国': 1, '为什么': 1, '以为': 1, '伊島ユウ': 1, '会断': 1, '低保': 1, '使用': 1, '全称': 1, '公告': 1, '内容': 1,
       '几日': 1, '几月': 1, '几点了': 1, '分享': 1, '北京': 1, '协议': 1, '原神': 1, '启动': 1, '呜呜': 1, '啊': 1, '嘞嘞': 1, '图片': 1,
       '坏耶': 1, '城说': 1, '够色': 1, '大使': 1, '天气': 1, '奇怪': 1, '如何': 1, '安装': 1, '寂寞': 1, '寿ち': 1, '尾巴': 1, '张宇': 1,
       '怪物': 1, '恶毒': 1, '我这': 1, '支持': 1, '改变': 1, '无邪': 1, '晚安': 1, '暖床': 1, '本群': 1, '条件': 1, '来自': 1, '杭州': 1,
       '欧派': 1, '比特币': 1, '沖田': 1, '没有': 1, '火涩': 1, '点火': 1, '版本': 1, '牙白': 1, '猎人': 1, '王道': 1, '现在': 1, '申请': 1,
       '知乎': 1, '科技': 1, '类型': 1, '绿逗': 1, '缩abc': 1, '耶': 1, '艳婚': 1, '英文': 1, '要塞': 1, '超时空': 1, '那天': 1, '野史': 1,
       '钉钉': 1, '飞书': 1, '高兴': 1, '魔王': 1}
```

The picture I used:
<img src="https://c.wallhere.com/photos/ab/5b/Iron_Man_artwork_white_background_simple_background_Marvel_Comics-1530491.jpg!d"></img>

Error message:
```
Traceback (most recent call last):
  File "W:/Python workspace/qqbotv2/SAGIRIBOT/functions/get_review.py", line 251, in <module>
    test2(dic)
  File "W:/Python workspace/qqbotv2/SAGIRIBOT/functions/get_review.py", line 245, in test2
    plt.imshow(wc.recolor(color_func=image_colors), interpolation="bilinear")
  File "S:\Anaconda3\envs\qqbot\lib\site-packages\wordcloud\wordcloud.py", line 696, in recolor
    self.layout_ = [(word_freq, font_size, position, orientation,
  File "S:\Anaconda3\envs\qqbot\lib\site-packages\wordcloud\wordcloud.py", line 697, in <listcomp>
    color_func(word=word_freq[0], font_size=font_size,
  File "S:\Anaconda3\envs\qqbot\lib\site-packages\wordcloud\color_from_image.py", line 55, in __call__
    raise ValueError('ImageColorGenerator is smaller than the canvas')
ValueError: ImageColorGenerator is smaller than the canvas
```

**Comment by amueller** [comment] 2021-04-06 23:19
@woreom sorry, are you running into a similar error?

**Comment by ZainNasrullah** [comment] 2021-10-24 01:30
fyi: if you are stilling running into this error ("ValueError: ImageColorGenerator is smaller than the canvas") when generating the word cloud from frequencies and using small font sizes, make sure there isn't a blank string ('') in your word dictionary. 

e.g., running this fixed things for me:
```
word_dict.pop('', None)
wc.generate_from_frequencies(word_dict)
```

in my case, the issue stemmed from a [(0,0) box size](https://github.com/amueller/word_cloud/blob/20dd15c2c9fb943eb72f383a81823144913360d0/wordcloud/color_from_image.py#L41) associated with the blank string.
