### ISSUE TITLE
query_integral_image module could not be found

### ISSUE THREAD

**Issue by Sharmilinag** [amueller/word_cloud#390] opened 2018-06-06 18:01 UTC

**Comment by amueller** [comment] 2018-06-06 18:16
How did you install?

**Comment by Sharmilinag** [comment] 2018-06-06 18:18
python -m pip install wordcloud

**Comment by amueller** [comment] 2018-06-06 18:18
and what's your code and traceback?

**Comment by Sharmilinag** [comment] 2018-06-06 18:21
C:\Users\Owner\PycharmProjects\Foodie\venv\Scripts\python.exe C:/Users/Owner/PycharmProjects/Foodie/Reviews.py
C:\Users\Owner\PycharmProjects\Foodie\venv\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Traceback (most recent call last):
  File "C:/Users/Owner/PycharmProjects/Foodie/Reviews.py", line 14, in <module>
    import wordcloud
  File "C:\Users\Owner\PycharmProjects\Foodie\venv\lib\site-packages\wordcloud\__init__.py", line 1, in <module>
    from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
  File "C:\Users\Owner\PycharmProjects\Foodie\venv\lib\site-packages\wordcloud\wordcloud.py", line 24, in <module>
    from .query_integral_image import query_integral_image
ImportError: DLL load failed: The specified module could not be found.

Process finished with exit code 1

**Comment by amueller** [comment] 2018-06-06 19:00
This is a duplicate of #356 see the discussion there.

**Closed by amueller** 2018-06-06 19:00 UTC
