### ISSUE TITLE
Saving result as .svg, instead of .png?

### ISSUE THREAD

**Issue by michaelsjackson** [amueller/word_cloud#509] opened 2019-11-13 15:30 UTC
Saving result images directly as .svg would be useful.

**Comment by amueller** [comment] 2019-11-13 16:56
see #163. Any help welcome. I had a hard time with the css for the font when I last tried to work on it.

**Comment by amueller** [comment] 2019-11-13 16:59
closing as duplicate of #58. See there also for the issues I ran into.

**Closed by amueller** 2019-11-13 16:59 UTC
