### ISSUE TITLE
generate_from_text throws ZeroDivisionError  when text is too short - (Python 2 only)

### ISSUE THREAD

**Issue by odovad** [amueller/word_cloud#237] opened 2017-03-15 10:50 UTC
Hello, 

I have an error when not enough word in my text. 
Here an example of code that does not work with Python 2.7.12, wordcloud 1.2.1 and also the latest wordcloud 1.3
It works if N is high.
For a value of 40 for N, it can works sometimes but not consistently.
```
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import random

w = WordCloud()


N = 10
tmp = ''

alea = 'azeyreuidlsdmqscnxwc'

for v in range(N):
    tmp = tmp + "".join([alea[random.randint(0, len(alea)-1)] for k in range(5)]) + ' '

THIS = tmp
w.generate_from_text(THIS)
f = plt.figure(figsize=(15,15))
plt.imshow(w)
plt.axis('off')
plt.show()
```

You'll find below the error encountered :

```
ZeroDivisionErrorTraceback (most recent call last)
<ipython-input-3-5c94f79d0090> in <module>()
     15 
     16 THIS = tmp
---> 17 w.generate_from_text(THIS)
     18 f = plt.figure(figsize=(15,15))
     19 plt.imshow(w)

/opt/conda/envs/py2k/lib/python2.7/site-packages/wordcloud/wordcloud.pyc in generate_from_text(self, text)
    528         """
    529         words = self.process_text(text)
--> 530         self.generate_from_frequencies(words)
    531         return self
    532 

/opt/conda/envs/py2k/lib/python2.7/site-packages/wordcloud/wordcloud.pyc in generate_from_frequencies(self, frequencies, max_font_size)
    410             rs = self.relative_scaling
    411             if rs != 0:
--> 412                 font_size = int(round((rs * (freq / float(last_freq))
    413                                        + (1 - rs)) * font_size))
    414             if random_state.random() < self.prefer_horizontal:

ZeroDivisionError: float division by zero
```

Thanks in advance.

**Comment by amueller** [comment] 2017-03-16 14:00
so THIS contains only a single word, right?

**Comment by odovad** [comment] 2017-03-16 16:54
Not only a single word; multiple words but a low number.

**Comment by amueller** [comment] 2017-03-16 17:08
can you give the content of ``tmp``? From the code it looks like a single word followed by a whitespace.

**Comment by odovad** [comment] 2017-03-17 09:48
tmp = 'zwrcq cndcu edyse uciec mayyd alsaq qxqwc dcsrc yyddu aqinc'

**Comment by amueller** [comment] 2017-03-17 17:57
oh sorry I misread that.
I can't reproduce the error though. Which version of wordcloud are you using? Can you try upgrading?

**Comment by odovad** [comment] 2017-03-20 12:52
I am not able to reproduce the error. it seems to work.
Maybe you were right and upgrading solved the problem.
Thanks.

**Comment by vishrantgupta** [comment] 2018-02-20 02:05
@amueller I am still getting this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Downloads\stackoverflow_tag_cloud-master\stackoverflow_tag_cloud-master\stackoverflow_users_taginfo.py", line 225, in tag_cloud
    max_words=len(info)).generate_from_frequencies(info)
  File "C:\Python\Python36\lib\site-packages\wordcloud\wordcloud.py", line 423, in generate_from_frequencies
    font_size = int(round((rs * (freq / float(last_freq))
ZeroDivisionError: float division by zero

```

**Comment by amueller** [comment] 2018-02-20 16:43
@vishrantgupta which version of wordcloud are you using?

**Comment by vishrantgupta** [comment] 2018-02-22 21:28
@amueller 1.3.1

**Comment by amueller** [comment] 2018-02-23 16:15
@vishrantgupta can you provide a minimum example to reproduce?

**Comment by amueller** [comment] 2018-04-17 18:37
Closing because no reproducible example. Happy to reopen with an example.

**Closed by amueller** 2018-04-17 18:37 UTC
