### ISSUE TITLE
Error installing Worldcloud on MacOS with Python 3.7

### ISSUE THREAD

**Issue by bazmattaz** [amueller/word_cloud#618] opened 2021-01-18 15:50 UTC
#### Description
While trying to install word cloud Mac OS using Python 3.7 I get the following error. 

#### Steps/Code to Reproduce

run:

pip3 install wordcloud

#### Expected Results

Wordcloud will install sucecsfully

#### Actual Results

```
`pip3 install wordcloud
Collecting wordcloud
  Using cached wordcloud-1.8.1.tar.gz (220 kB)
Requirement already satisfied: numpy>=1.6.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from wordcloud) (1.19.5)
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from wordcloud) (8.1.0)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from wordcloud) (3.3.3)
Requirement already satisfied: python-dateutil>=2.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib->wordcloud) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib->wordcloud) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib->wordcloud) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib->wordcloud) (0.10.0)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from cycler>=0.10->matplotlib->wordcloud) (1.15.0)
Building wheels for collected packages: wordcloud
  Building wheel for wordcloud (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8p/yq739_0x5r332jnb84pm62rx2vtwwd/T/pip-install-b4wmib26/wordcloud_c08306f80b0f4a0c949adbb0b105f820/setup.py'"'"'; __file__='"'"'/private/var/folders/8p/yq739_0x5r332jnb84pm62rx2vtwwd/T/pip-install-b4wmib26/wordcloud_c08306f80b0f4a0c949adbb0b105f820/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/8p/yq739_0x5r332jnb84pm62rx2vtwwd/T/pip-wheel-33satil3
       cwd: /private/var/folders/8p/yq739_0x5r332jnb84pm62rx2vtwwd/T/pip-install-b4wmib26/wordcloud_c08306f80b0f4a0c949adbb0b105f820/
  Complete output (24 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/_version.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/tokenization.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/wordcloud.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/color_from_image.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/__main__.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/stopwords -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  UPDATING build/lib.macosx-10.9-x86_64-3.7/wordcloud/_version.py
  set build/lib.macosx-10.9-x86_64-3.7/wordcloud/_version.py to '1.8.1'
  running build_ext
  building 'wordcloud.query_integral_image' extension
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/wordcloud
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c wordcloud/query_integral_image.c -o build/temp.macosx-10.9-x86_64-3.7/wordcloud/query_integral_image.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: wordcloud
    Running setup.py install for wordcloud ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8p/yq739_0x5r332jnb84pm62rx2vtwwd/T/pip-install-b4wmib26/wordcloud_c08306f80b0f4a0c949adbb0b105f820/setup.py'"'"'; __file__='"'"'/private/var/folders/8p/yq739_0x5r332jnb84pm62rx2vtwwd/T/pip-install-b4wmib26/wordcloud_c08306f80b0f4a0c949adbb0b105f820/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/8p/yq739_0x5r332jnb84pm62rx2vtwwd/T/pip-record-gbuzmcyk/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/wordcloud
         cwd: /private/var/folders/8p/yq739_0x5r332jnb84pm62rx2vtwwd/T/pip-install-b4wmib26/wordcloud_c08306f80b0f4a0c949adbb0b105f820/
    Complete output (24 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/_version.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/tokenization.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/wordcloud.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/color_from_image.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/__main__.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/stopwords -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    UPDATING build/lib.macosx-10.9-x86_64-3.7/wordcloud/_version.py
    set build/lib.macosx-10.9-x86_64-3.7/wordcloud/_version.py to '1.8.1'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/wordcloud
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c wordcloud/query_integral_image.c -o build/temp.macosx-10.9-x86_64-3.7/wordcloud/query_integral_image.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8p/yq739_0x5r332jnb84pm62rx2vtwwd/T/pip-install-b4wmib26/wordcloud_c08306f80b0f4a0c949adbb0b105f820/setup.py'"'"'; __file__='"'"'/private/var/folders/8p/yq739_0x5r332jnb84pm62rx2vtwwd/T/pip-install-b4wmib26/wordcloud_c08306f80b0f4a0c949adbb0b105f820/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/8p/yq739_0x5r332jnb84pm62rx2vtwwd/T/pip-record-gbuzmcyk/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/wordcloud Check the logs for full command output.`
```

#### Versions

```
Darwin-19.6.0-x86_64-i386-64bit
Python 3.7.9 (v3.7.9:13c94747c7, Aug 15 2020, 01:31:08) 
[Clang 6.0 (clang-600.0.57)]
NumPy 1.19.5
matplotlib 3.3.3
```

**Comment by amueller** [comment] 2021-01-20 00:29
thanks, I think this is a duplicate of #613

**Comment by Danning666** [comment] 2022-03-19 18:42
I meet exactly the same problem today as you did! Too excited to see this issue.

**Closed** 2023-04-27 21:01 UTC
