### ISSUE TITLE
word cloud error

### ISSUE THREAD

**Issue by aniketbhunia007** [amueller/word_cloud#286] opened 2017-08-17 06:02 UTC
No module named 'wordcloud'
It is showing this.
While installing through conda, this error is shown.
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - wordcloud -> python 3.4*

**Comment by amueller** [comment] 2017-08-17 14:53
Which conda channel are you using? If this is the main channel, we can ask the conda folks to update. If it's conda-forge I (or someone else) needs to update the feedstock to build with python 3.6

**Comment by amueller** [comment] 2017-09-28 15:29
closing as duplicate of #232.

**Closed by amueller** 2017-09-28 15:29 UTC
