### ISSUE TITLE
Allow for numbers in cloud?

### ISSUE THREAD

**Issue by jaradc** [amueller/word_cloud#142] opened 2016-03-23 16:35 UTC
Amazing tool. I am trying to allow for numbers (ex: 1, 14, 209) in the word cloud.  I thought I could achieve this by editing the `regexp=` in the `WordCloud(regexp=pattern)` but it doesn't seem to be working for me.  If I were to set a variable named `allow_numbers` to `True`, is there something wrong with my regex?

```
if allow_numbers:
  pattern = r'(\w+|\w)'
else:
  pattern = r'\w[\w\']+'
```

**Comment by amueller** [comment] 2016-03-24 16:14
there is an additional "isdigit" check in process_text that you'd need to skip. You can add a parameter if you like.

**Comment by amueller** [comment] 2018-04-17 18:43
duplicate of #202.

**Closed by amueller** 2018-04-17 18:43 UTC
