### ISSUE TITLE
UnsatisfiableError Python 3.6 Linux64

### ISSUE THREAD

**Issue by hhain** [amueller/word_cloud#235] opened 2017-03-12 13:43 UTC
During conda install -c amueller wordcloud=1.2.2 occures an UnsatisfiableError as Python 3.6 does not seem to be compatible with openssl 1.0.1 / xz 5.0.5 where a downgrade to Python 3.5 would be needed.

Accordingly the conda-forge build fails in the same manner but would require an even lower Python 3.4 Version to satisfy the build.

Is there a way around this issue?

**Comment by amueller** [comment] 2017-03-13 21:22
Please post this issue on the conda-forge tracker.
There is no conda package for wordcloud right now unfortunately - happy to take your help on this ;)

I'm not sure why there is a dependency on openssl. What exactly creates this conflict?

**Comment by amueller** [comment] 2017-09-28 15:30
Closing as duplicate of #232.

**Closed by amueller** 2017-09-28 15:30 UTC
