### ISSUE TITLE
Error while trying to import wordcloud

### ISSUE THREAD

**Issue by ritzritu** [amueller/word_cloud#364] opened 2018-04-17 17:03 UTC
I am getting the following error while trying to import wordcloud

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-12-1faa7b3f23e2> in <module>()
      1 # Import lib for word cloud visualization
----> 2 from wordcloud.wordcloud import WordCloud

C:\ProgramData\Anaconda3\lib\site-packages\wordcloud\__init__.py in <module>()
----> 1 from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
      2                         get_single_color_func)
      3 from .color_from_image import ImageColorGenerator
      4 
      5 __all__ = ['WordCloud', 'STOPWORDS', 'random_color_func',

C:\ProgramData\Anaconda3\lib\site-packages\wordcloud\wordcloud.py in <module>()
     17 from operator import itemgetter
     18 
---> 19 from PIL import Image
     20 from PIL import ImageColor
     21 from PIL import ImageDraw

C:\ProgramData\Anaconda3\lib\site-packages\PIL\Image.py in <module>()
     54     # Also note that Image.core is not a publicly documented interface,
     55     # and should be considered private and subject to change.
---> 56     from . import _imaging as core
     57     if PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):
     58         raise ImportError("The _imaging extension was built for another "

ImportError: DLL load failed: The specified module could not be found.
```

**Comment by amueller** [comment] 2018-04-17 17:17
duplicate of #356. Can you do ``from PIL import Image`` or ``import Image``?

**Closed** 2018-04-17 18:45 UTC
